version: "3.7"
services:
  app:
    container_name: docker-node-mysql
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db
  db:
    container_name: excercise_db
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysqladmin ping -h127.0.0.1 -uroot -ptest12 --silent"
      interval: 10s
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=excercise_tracker
volumes:
  db_data:
